CREATE TABLE ingredient (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name varchar(255) NOT NULL,
    quantity integer NOT NULL,
    max_quantity integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE orders (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name_recipe varchar(255) NOT NULL,
    created_at timestamp(6) NOT NULL,
    PRIMARY KEY (id)
);
CREATE INDEX idx_order_nameRecipe_createdAt ON orders (name_recipe, created_at);
CREATE TABLE recipe (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name varchar(255) NOT NULL,
    ingredients varchar(255),
    preparation_time integer NOT NULL,
    PRIMARY KEY (id)
);

